service: hithlum-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: function/hello.main
    events:
      - httpApi:
          path: /hello
          method: get

plugins:
  - serverless-esbuild
