service: hithlum
frameworkVersion: "3"

plugins:
  - serverless-esbuild
  - serverless-lift
  - serverless-plugin-conditional-functions
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x
  stage: ${opt:stage}
  httpApi:
    cors: true
  environment:
    ARTICLE_QUEUE: ${construct:articleQueue.queueUrl}
    ARTWORK_BUCKET: ${construct:artwork.bucketName}
    MANDOS_URL: ${self:custom.global.mandosUrl.${self:provider.stage}}
    STAGE: ${self:provider.stage}
    TABLE: ${self:service}-${opt:stage}-table-v3
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:*:*:table/${self:provider.environment.TABLE}
            - arn:aws:dynamodb:*:*:table/${self:provider.environment.TABLE}/index/*

custom: ${file(./serverless/custom.yml)}
functions: ${file(./serverless/functions.yml)}

resources:
  Resources:
    hithlumTableV3:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties: ${file(./serverless/table-properties-v3.js)}

constructs:
  articleQueue:
    type: queue
    worker:
      handler: function/article-queue-worker.main

  frontend:
    type: single-page-app
    path: ../frontend/dist
    domain:
      - ${self:custom.global.domain.${self:provider.stage}}
      - www.${self:custom.global.domain.${self:provider.stage}}
    certificate: ${self:custom.global.certificate.${self:provider.stage}}

  artwork:
    type: storage
