service: hithlum-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: function/hello.main
    events:
      - httpApi:
          path: /hello
          method: get
  graphql:
    handler: function/graphql/graphql.main
    events:
      - http:
          path: /graphql
          method: post
          cors: true
      - http:
          path: /graphql
          method: get
          cors: true

plugins:
  - serverless-esbuild
